# Generated by Django 3.2.6 on 2021-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
