# Generated by Django 3.2.6 on 2021-08-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menu_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
