# Generated by Django 3.2.6 on 2021-08-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menu_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
