# Generated by Django 3.2.6 on 2021-08-09 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
            preserve_default=False,
        ),
    ]
